### PR TITLE
Update and rename bug_report.md to bug_report.yml

### PR DESCRIPTION
**Pull request by The-Repo-Club**
Just an idea i don't know if you like it this way or not though?

### CODE REVIEW

**Comment by The-Repo-Club** [comment]
this way it forces people to fill it out and not just remove the text and put what they want in the text box? i hope you get the idea where i was going with this.

**Comment by jooooscha** [comment]
Wow, this is great. Thanks. Was wondering if such a thing is possible

**Comment by jooooscha** [comment]
If you are ok with my changes, I will merge this

**Comment by The-Repo-Club** [comment]
I'm happy if you are

**Comment by The-Repo-Club** [comment]
Why did you change us to me then change I to we? Is it us and we or me and I

**Comment by jooooscha** [comment]
Where? I cannot find it. Btw, you can add comments directly to a specific line

**Comment by The-Repo-Club** [comment]
oh nvm you changed them to math :) mobile viewing looked weird

**Pull request merged**
