### PR TITLE
Add a swipe down gesture and improve other swipe gestures

### PR DESCRIPTION
**Pull request by The-Repo-Club**
Add a swipe down gesture

Signed-off-by: The-Repo-Club <wayne6324@gmail.com>

### CODE REVIEW

**Comment by jooooscha** [comment]
This does currently not support using the old "pull down the notification drawer" function, does it?

**Comment by The-Repo-Club** [comment]
> This does currently not support using the old "pull down the notification drawer" function, does it?

no it replaces the notification pull down. i may change it so if set to none then it adds back the notification draw

**Comment by jooooscha** [comment]
I think that is a good idea for now

**Comment by The-Repo-Club** [comment]
might need them 2 other functions lol fixed a bug that wouldn't let me re enable it if i clicked disable

**Comment by The-Repo-Club** [comment]
> I think that is a good idea for now

I made it so that if SwipeDown is disabled then expandNotificationDrawer()

**Comment by jooooscha** [comment]
I have tested the current version, and I find it irritating that `disable` actually means activate "show notifications". I think we should make it a three-way switch that can be on "show notifications" "open app" or "disabled".
I will test it on my device and see how this could be done

**Comment by The-Repo-Club** [comment]
Ya I agree that would be a better way to do it :)

**Comment by jooooscha** [comment]
Did you disable "Edits from Maintainers"? I cannot push changes to this PR

This is what I mean: [link](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)

**Comment by The-Repo-Club** [comment]
> Did you disable "Edits from Maintainers"? I cannot push changes to this PR

there is no option... maybe cus this is the main branch?

**Comment by jooooscha** [comment]
This would be my proposl for it. If you don't have any additions to it, this would need to be implemented for the other swipe directions too

**Comment by The-Repo-Club** [comment]
> This would be my proposl for it. If you don't have any additions to it, this would need to be implemented for the other swipe directions too

this looks good to me, so the other directions would be the same but just not have the app notification draw as an option?

**Comment by jooooscha** [comment]
Why shouldn't they have that option too?

**Comment by The-Repo-Club** [comment]
> Why shouldn't they have that option too?

up left and right don't really need the `notification draw ` but that is my opinion

**Comment by jooooscha** [comment]
> ps. the lock screen option also doesn't do anything on the pixel 7

This is not ready yet. I also started to implement the other actions, but thats not finished yet, also. I will finish it the next days

**Comment by jooooscha** [comment]
> up left and right don't really need the notification draw but that is my opinion

But it's only an option and makes the implementation much easier. So I don't think we need to over-engineer this

**Comment by The-Repo-Club** [comment]
> > ps. the lock screen option also doesn't do anything on the pixel 7
> 
> This is not ready yet. I also started to implement the other actions, but thats not finished yet, also. I will finish it the next days

ok sounds good mate :)

**Comment by The-Repo-Club** [comment]
Fixed and it will now build :)

**Comment by jooooscha** [comment]
Great. Thanks.

Let me test this tommorrow. I also want two check how this looks from a new install and from a direct upgrade from the last version.

If everything looks good, this could be merged soon

**Comment by The-Repo-Club** [comment]
> If everything looks good, this could be merged soon

i renamed my build but same thing :)

Peek 2022-12-11 21-26

**Comment by The-Repo-Club** [comment]
[This](https://github.com/OlauncherCF/OlauncherCF/pull/220/commits/8c45367e007ba5d0a11ac66d1ed97930723c4b07) should fix that issue from above

**Comment by jooooscha** [comment]
I expanded the new action options to also work with the double tap gesture.

I think this is feature complete then. I will check everything again tonight. After that this should be ready to be merged.

**Comment by The-Repo-Club** [comment]
Ok I'll give it a test after work on a clean install too :)

**Comment by jooooscha** [comment]
Give a couple of days to go over it again. Don't want to rush this :)

I will merge it as soon as I am done

**Comment by jooooscha** [comment]
Before we merge we should decrease the area in which one can swipe down. Currently, I cannot open the notification drawer, without activating the swipe down action. This wasnt a problem before, because the swipe down action did open the notifocation area, but it becomes a problem when the swipe down action is, for example, set to locking the screen.

**Comment by The-Repo-Club** [comment]
> Before we merge we should decrease the area in which one can swipe down. Currently, I cannot open the notification drawer, without activating the swipe down action. This wasnt a problem before, because the swipe down action did open the notifocation area, but it becomes a problem when the swipe down action is, for example, set to locking the screen.

This should not be an issue if you are swiping down from the top bar but when that is not enabled then yes anything below the date and time should be the only swipe zone :)

**Comment by jooooscha** [comment]
Especially when the top bar is hidden, this has been an issue, at least on my device.

But, then again, it should not be hard to fix. I will take a look at it, as soon as I have time

**Comment by The-Repo-Club** [comment]
> Especially when the top bar is hidden, this has been an issue, at least on my device.
> 
> But, then again, it should not be hard to fix. I will take a look at it, as soon as I have time

ya the pixel series phones don't really seem to have this issue cus as soon as you touch the screen to swipe from the bar the bar will rapier if it is hidden

**Comment by jooooscha** [comment]
Ok, this did turn out to be a bigger PR than expected, but we got there and this should be ready now.
I certainly found code that can be improved, but for now this should be enough.

In my tests, the update from the last version should be friction less

**Pull request merged**
