### PR TITLE
Load and store settings to json file

### LINKED ISSUE #54: [Feature Request] Backup/Restore Settings
The app itself is great! I really love the text-based style.

As I rename several apps to unique names (to search faster), it would be appreciated if you could add a way to backup & restore OlauncherCF settngs.

### PR DESCRIPTION
**Pull request by jooooscha**
closes #54 
Replaces #69

### CODE REVIEW

**Comment by The-Repo-Club** [comment]
this [documents-files](https://developer.android.com/training/data-storage/shared/documents-files) may help with this?

**Comment by jooooscha** [comment]
Thanks, but that part is already sorted out. It did basically work already but I had some weird bugs everytime after restoring a backup. Since then I did not follow through with this PR. Maybe I should pick it up again

**Comment by The-Repo-Club** [comment]
By bug do you mean apps would vanish ?

**Comment by jooooscha** [comment]
I am not sure anymore. But I think there were some problems with the apps list not showing up at all. It was something seemingly unrelated. I will have to take a look at it again to be sure.

The problem is not that this is not compiling.

**Comment by The-Repo-Club** [comment]
Ya the apps list would say no apps found when you restore. Ya that line will come back with not enough information

**Comment by jooooscha** [comment]
Finally, got it. This issue was originally created 1. July 2022 That's a long time. But there we are :)

closes #54

**Pull request merged**
