### PR TITLE
fix: build singed apk

### PR DESCRIPTION
**Pull request by The-Repo-Club**
[Example](https://github.com/HeCodes2Much/mLauncher/releases/tag/1.2.1)

Not too sure how to get `secrets.SIGNING_KEY` on windows or mac but below is Linux

```
openssl base64 < foo.jks | tr -d '\n' > foo.jks.txt
```

### CODE REVIEW

**Comment by The-Repo-Club** [comment]
if you want the command on linux to get the `secrets.SIGNING_KEY`

```
openssl base64 < foo.jks | tr -d '\n' > foo.jks.txt
```

**Comment by The-Repo-Club** [comment]
The fail check is due to the current signing that you put in place not the now one btw

**Comment by The-Repo-Club** [comment]
[The-Repo-Club/OlauncherCF](https://github.com/The-Repo-Club/OlauncherCF/releases) example

**Comment by The-Repo-Club** [comment]
The fail check above is due to the current branch being broken and not this PR

**Comment by The-Repo-Club** [comment]
make sure you have the keys set up for this to work.... you need all 4 keys

**Comment by jooooscha** [comment]
I have them set up.

> Short read of DER length

This rather suggests I have mixed something with the keys. Will look at this probably after christmas

**Comment by The-Repo-Club** [comment]
SIGNING_KEY = the key from said command (reallllly long sting of text)

the others should match these if building from Android Studio
image

**Comment by The-Repo-Club** [comment]
also you may need to add 
```
env:
        # override default build-tools version (29.0.3) -- optional
        BUILD_TOOLS_VERSION: "30.0.2"
```

**Pull request merged**
