### PR TITLE
fix: Fixes setCurrentState error

### PR DESCRIPTION
**Pull request by HeCodes2Much**
```
java.lang.IllegalStateException: Method setCurrentState must be called on the main thread
```

### CODE REVIEW

**Comment by jooooscha** [comment]
Please add more context. Also, if you mark this as draft, I assume your still want to change things? Otherwise, please set to: Ready for review

**Comment by The-Repo-Club** [comment]
oh sorry ya its ready not it passed :)

**Comment by jooooscha** [comment]
So there is no immediate problem with the current implementation?

**Comment by The-Repo-Club** [comment]
No it just fixes the issue stated but the app still works.

**Comment by jooooscha** [comment]
I cannot confirm the occurrence of this exception. Please add any information on how to reproduce this.
Long-clicking on the home screen does not seem to cause this

**Pull request closed without merging**
